name: Build and Deploy
on: 
  push:
    branches: 
      - main
env:
  CI: ""
permissions: 
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Deploy ğŸš€ # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          git config --global user.name "JakeLDev"
          git config --global user.email "me@jakelyell.dev"
          npm ci
          npm run deploy

      # - name: Deploy ğŸš€
      #   uses: JamesIves/github-pages-deploy-action@v4.3.3
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: build # The folder the action should deploy.